LutronQuantum/Controllers/LutronQuantumController.cs
using LutronQuantum.Common;
using LutronQuantum.Models.LutronObix;
using LutronQuantum.Obix.ObixActions;
using Obix_JACE_V1.Obix;
using Obix_JACE_V1.Obix.ObixActions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace LutronQuantum.Controllers
{
    [RoutePrefix("api/LutronQuantum")]
    public class LutronQuantumController : ApiController
    {
        ObixClientInit obixClientInit;
        public LutronQuantumController()
        {
            obixClientInit = new ObixClientInit();
        }   
              

        [HttpGet]
        [Route("GetSceneRangeList")]
        public IHttpActionResult GetSceneRangeList()
        {
            var sceneRangeList = ReadActions.GetEnumList<LightSceneEnum>();
            return Ok(sceneRangeList);
        }

        [HttpGet]
        [Route("GetCurrentValue/{deviceTypeId:int}")]
        public IHttpActionResult GetCurrentLightState(int deviceTypeId)
        {
            var deviceLst = ReadActions.GetCurrentLightState(deviceTypeId);
            return Ok(deviceLst);
        }

      
        [HttpPost]
        [Route("SaveLightLevel")]
        public IHttpActionResult SaveLightLevel(DeviceEntity deviceObj)
        {
            WriteActions.WriteLightLevel(deviceObj);
            ReadActions.SaveCurrentLutronQuatumDetail();
            return Ok();
        }

        [HttpPost]
        [Route("SaveLightState")]
        public IHttpActionResult SaveLightState(DeviceEntity deviceObj)
        {
            WriteActions.WriteLightState(deviceObj);
            ReadActions.SaveCurrentLutronQuatumDetail();
            return Ok();
        }

        [HttpPost]
        [Route("SaveDeviceScene")]
        public IHttpActionResult SaveDeviceScene(SceneEntity sceneObj)
        {
            WriteActions.WriteDeviceScene(sceneObj);
            ReadActions.SaveCurrentLutronQuatumDetail();
            return Ok();
        }

        [HttpGet]
        [Route("GetsCurrentDeviceLevel")]
        public IHttpActionResult GetsCurrentDeviceLevel()
        {           
            var deviceDetail= ReadActions.GetsCurrentDeviceLevel();
            return Ok(deviceDetail);
        }

    }
}

LutronQuantum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Obix Driver</title>
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-slider.min.css" rel="stylesheet" />
    <link href="~/Content/RangeSlidar.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-slider.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/datatable.css" rel="stylesheet" />

    @*@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Obix Driver", "LutronQuantum", "Home", new { area = "" }, new { @class = "navbar-brand"})
            </div>
          
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - Softweb Solution</p>
        </footer>*@
    </div>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/datatable.min.js"></script>>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)*@
</body>
</html>